### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Audax23** [netgen-layouts/layouts-sylius-bitbag#8]
Hi, 
Where can i find complete documentation to use this package? 
and learn how to use bitbag cms plugin on Netgen Layout sur Sylius?
Thanks

**Comment by emodric** [comment]
Hi @Audax23 ! There is no documentation unfortunately, since this plugin is still in testing stage. In reality though, this package requires very little to none documentation as it only adds the possibility for BitBag entites to be used as items in Netgen Layouts grid/list blocks (similar to how Sylius products can be used). Apart from that, there are no user facing features available in this bundle.

I hope this answers your question.

**Comment by Audax23** [comment]
Hi @emodric ,
Yes that answers my question.
THANKS
